# Q1. What is a Python library? Why do we use Python libraries?

# Ans:1 
**What is the Python Library?**

A Python library is a collection of pre-written code and functionalities that can be used by developers to perform common tasks without having to write the code from scratch. These libraries are designed to be reusable and provide a set of functions, modules, and classes that address specific needs. Python, being a versatile programming language, has a rich ecosystem of libraries that cover a wide range of domains such as data analysis, machine learning, web development, and more.

  **Here are some key reasons why we use Python libraries:**

- `Efficiency:` Libraries save time and effort by providing pre-implemented solutions for common tasks. Developers can leverage existing code rather than reinventing the wheel, leading to faster development cycles.

- `Productivity:` Python libraries enhance productivity by allowing developers to focus on higher-level aspects of their projects. With ready-made functions and modules, they can build on a solid foundation and achieve more in less time.

- `Community Support:` The Python community actively contributes to the development of libraries. This means that there is a wealth of collective knowledge and expertise available, making it easier to find solutions to problems and share best practices.

- `Quality and Reliability:` Well-established Python libraries are often thoroughly tested and optimized for performance. This helps ensure the reliability and quality of the code, reducing the likelihood of errors and bugs.

- `Domain-specific Functionality:` Python libraries cater to various domains, such as data science, machine learning, web development, and more. These specialized libraries provide tools and functions tailored to specific needs, enabling developers to work efficiently within their chosen field.

- `Open Source Collaboration:` Many Python libraries are open source, allowing developers to inspect, modify, and contribute to the codebase. This collaborative nature fosters innovation and continuous improvement within the community.

- `Interoperability:` Python libraries are designed to work seamlessly with each other, promoting interoperability. Developers can combine functionalities from different libraries to create powerful and integrated solutions.

# Q2. What is the difference between Numpy array and List?

# Ans: 2 

Numpy arrays and lists in Python are both used to store collections of data, but they have some fundamental differences in terms of functionality, performance, and usage. 

**Here are some key distinctions:**

**1.Data Type:**

- `List:` Lists in Python can hold elements of different data types. You can have a mix of integers, floats, strings, and other objects in a single list.
- `Numpy Array:` Numpy arrays, on the other hand, are homogeneous, meaning all elements must be of the same data type. This homogeneity allows for more efficient storage and operations.


**2.Performance:**

- `List:` Lists are general-purpose and versatile, but they are not optimized for numerical operations. Iterating through a list can be slower for large datasets.
- `Numpy Array:` Numpy arrays are designed for numerical operations and are implemented in C, which makes them more efficient for numerical computations. Numpy operations are vectorized, meaning they operate on entire arrays at once, leading to better performance compared to element-wise operations on lists.


**3.Memory Efficiency:**

- `List:` Lists in Python have more overhead in terms of memory usage because they store additional information, such as the type of each element and the size of the list.
- `Numpy Array:` Numpy arrays are more memory-efficient as they use a contiguous block of memory to store data and require less overhead.

**4.Convenience and Expressiveness:**

- `List:` Lists are more flexible and easier to work with for general-purpose tasks. They support a variety of methods and can be easily modified (appending, inserting, deleting elements).
- `Numpy Array:` Numpy arrays are optimized for numerical operations, providing a wide range of mathematical functions that can be applied to entire arrays. They are less flexible than lists in terms of modification but excel in numerical computations.


**5.Functionality:**

- `List:` Lists offer a broader range of functionalities, including versatile methods for manipulation, slicing, and iteration.
- `Numpy Array:` Numpy arrays provide specialized functions for mathematical operations, such as linear algebra, statistical analysis, and mathematical functions.

# Q3. Find the shape, size and dimension of the following array?
[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [1]:
# Ans:3

import numpy as np 

arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])
                    
# shape of the array 
shape = arr.shape

# size of array 
size = arr.size

# Dimension of array
D = arr.ndim

print('Shape of array is:', shape)
print('Size of array is:', size)
print('Dimension of array is:', D)

Shape of array is: (3, 4)
Size of array is: 12
Dimension of array is: 2


# Q4. Write python code to access the first row of the following array?
[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [2]:
# Ans: 4 

arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])

row_1 = arr[0]
print('Frist Row of the Array is:', row_1)

Frist Row of the Array is: [1 2 3 4]


# Q5. How do you access the element at the third row and fourth column from the given numpy array?
[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [3]:
# Ans: 5 

arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])

element = arr[2,3]
print('Element at the third row and fourth column is:', element)

Element at the third row and fourth column is: 12


# Q6. Write code to extract all odd-indexed elements from the given numpy array?
[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [4]:
# Ans: 6

arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])

# Extracting all odd-indexed elements
odd_elements = arr[:, 1::2].flatten()    # flatten is used to convert the resulting 2D array into a 1D array.

print("Odd-Indexed Elements:", odd_elements)

Odd-Indexed Elements: [ 2  4  6  8 10 12]


# Q7. How can you generate a random 3x3 matrix with values between 0 and 1?

In [5]:
# Ans:7 

# generate a random 3x3 matrix with values between 0 and 1
random_matrix = np.random.rand(3, 3)

print("Random 3x3 Matrix:")
print(random_matrix)

Random 3x3 Matrix:
[[0.88141548 0.80889295 0.21781634]
 [0.76181583 0.54216097 0.00280662]
 [0.67438852 0.51467587 0.7819966 ]]


# Q8. Describe the difference between np.random.rand and np.random.randn?

Ans: 8 

np.random.rand and np.random.randn are both functions from the NumPy library in Python that generate random numbers, but they differ in how they distribute those numbers.

**np.random.rand:**

- `Distribution:` It generates random numbers from a uniform distribution over the interval [0, 1).
- `Arguments:` You pass the dimensions of the array you want as arguments (e.g., np.random.rand(3, 3) for a 3x3 matrix).
- `Values:` All values are equally likely to occur, and each value has an equal probability of being chosen.

In [6]:
# for example 
random_matrix = np.random.rand(3, 3)
random_matrix

array([[0.19120184, 0.94394127, 0.25807911],
       [0.68273318, 0.43634009, 0.64633322],
       [0.86141569, 0.75691532, 0.98669427]])

**np.random.randn:**

- `Distribution:` It generates random numbers from a standard normal distribution (mean = 0, standard deviation = 1).
- `Arguments:` You pass the dimensions of the array you want as arguments (e.g., np.random.randn(3, 3) for a 3x3 matrix).
- `Values:` The values are more likely to be close to 0, with a probability decreasing as you move away from 0. It follows a bell-shaped curve, also known as a normal or Gaussian distribution.

In [7]:
random_matrix_normal = np.random.randn(3, 3)
random_matrix_normal

array([[-1.31069239, -0.03565312, -2.29928603],
       [ 0.63276527, -1.04554152,  1.22646968],
       [-0.96589129,  0.75365862,  0.37431484]])

# Q9. Write code to increase the dimension of the following array?
[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [8]:
# Ans:9 

arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])

# Increase the dimension using numpy.expand_dims
expanded_array = np.expand_dims(arr, axis=2)

print("Original Array Shape:", arr.shape)
print("Expanded Array Shape:", expanded_array.shape)

Original Array Shape: (3, 4)
Expanded Array Shape: (3, 4, 1)


# Q10. How to transpose the following array in NumPy?
[[1, 2, 3, 4]

 [5, 6, 7, 8],

 [9, 10, 11, 12]]

In [9]:
# Ans: 10 

arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])

# transposed array 
trans = arr.T
print(trans)

[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


# Q11. Consider the following matrix:
`Matrix A:` [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]

`Matrix B:` [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]

**Perform the following operation using Python1**
1. Index wise multiplication
2. Matrix multiplication
3. Add both the matrics
4. Subtract matrix B from A
5. Divide matrix B by A

In [10]:
# Ans: 11
matrix_A = np.array([[1, 2, 3, 4],
                     [5, 6, 7, 8],
                     [9, 10, 11, 12]])

matrix_B = np.array([[1, 2, 3, 4],
                     [5, 6, 7, 8],
                     [9, 10, 11, 12]])


# 1. Index wise multiplication
index_wise_multiplication = matrix_A * matrix_B

# 2. Matrix multiplication
matrix_multiplication = np.dot(matrix_A, matrix_B.T)  # Transposing B for proper multiplication

# 3. Add both matrices
matrix_addition = matrix_A + matrix_B

# 4. Subtract matrix B from A
matrix_subtraction = matrix_A - matrix_B

# 5. Divide matrix B by A
matrix_division = np.divide(matrix_B, matrix_A)

# Display results
print("1. Index wise multiplication:")
print(index_wise_multiplication)

print("\n2. Matrix multiplication:")
print(matrix_multiplication)

print("\n3. Matrix addition:")
print(matrix_addition)

print("\n4. Matrix subtraction:")
print(matrix_subtraction)

print("\n5. Matrix division:")
print(matrix_division)

1. Index wise multiplication:
[[  1   4   9  16]
 [ 25  36  49  64]
 [ 81 100 121 144]]

2. Matrix multiplication:
[[ 30  70 110]
 [ 70 174 278]
 [110 278 446]]

3. Matrix addition:
[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]

4. Matrix subtraction:
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]

5. Matrix division:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


# Q12. Which function in Numpy can be used to swap the byte order of an array?

# Ans:12

In NumPy, the byteswap function can be used to swap the byte order of an array. The byteswap function swaps the byte order of the elements in the array, and you can specify the byte order using the byteorder parameter. The default value of byteorder is '>', which means big-endian byte order.

In [11]:
# Creating an array with a specific byte order
original_array = np.array([1, 2, 3, 4], dtype='int32')

# Swaping the byte order using byteswap
swapped_array = original_array.byteswap()

print("Original Array:")
print(original_array)

print("\nSwapped Array:")
print(swapped_array)

Original Array:
[1 2 3 4]

Swapped Array:
[16777216 33554432 50331648 67108864]


# Q13. What is the significance of the np.linalg.inv function?

# Ans: 13

The np.linalg.inv function in NumPy is used to compute the inverse of a square matrix. It's important for solving systems of linear equations, computing eigenvalues/eigenvectors, and assessing the numerical stability of matrix operations. The inverse of a matrix 
A is denoted as A^-1 and satisfies

**A x A^-1 = A^-1 x A = I**

where I is the identity matrix. The function is specifically designed for square matrices and assumes they are of full rank.







# Q14. What does the np.reshape function do, and how is it used?

# Ans: 14

The np.reshape function in NumPy is used to change the shape of an array without changing its data. It allows you to rearrange the elements of an array into a new shape while maintaining the same data.

In [12]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

reshaped_arr = np.reshape(arr,(6,))


print("Original Array:")
print(arr)

print("\nReshaped Array:")
print(reshaped_arr)

Original Array:
[[1 2 3]
 [4 5 6]]

Reshaped Array:
[1 2 3 4 5 6]


# Q15. What is broadcasting in Numpy?

# Ans: 15

Broadcasting in NumPy is a feature that enables efficient operations on arrays with different shapes. When performing element-wise operations, NumPy automatically adjusts the shapes of the arrays, allowing them to be compatible for computation. Broadcasting occurs when dimensions are either equal or one of them is 1. In such cases, NumPy virtually replicates the smaller array to match the shape of the larger one.

This feature simplifies array operations, eliminating the need for explicit loops or manual replication of data. Broadcasting is particularly valuable in scenarios where arrays of different shapes need to be combined, making code more concise and readable.

In [13]:
# For example, consider adding a 1D array to a 2D array:
A = np.array([[1, 2, 3],
              [4, 5, 6]])

B = np.array([10, 20, 30])

result = A + B
print(result)

[[11 22 33]
 [14 25 36]]
